---
title: "Dataset Testing"
author: "Alexander Thiersch"
date: "3/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Step 0: Link to Datasets

https://www.countyhealthrankings.org/explore-health-rankings/rankings-data-documentation/national-data-documentation-2010-2019



Step 1: Loading Datasets
```{r}
#Loading RWJF Datasets from 2012-2019
library(readr)
#Load 2019 Dataset
analytic_data2019 <- read_csv("~/Documents/GitHub/DATS-6101-group-6/data/raw/analytic_data2019.csv")

#Load 2018 Dataset
analytic_data2018 <- read_csv("~/Documents/GitHub/DATS-6101-group-6/data/raw/analytic_data2018_0.csv")


#Load 2017 Dataset
analytic_data2017 <- read_csv("~/Documents/GitHub/DATS-6101-group-6/data/raw/analytic_data2017.csv")


#Load 2016 Dataset
analytic_data2016 <- read_csv("~/Documents/GitHub/DATS-6101-group-6/data/raw/analytic_data2016.csv")


#Load 2015 Dataset
analytic_data2015 <- read_csv("~/Documents/GitHub/DATS-6101-group-6/data/raw/analytic_data2015.csv")


#Load 2014 Dataset
analytic_data2014 <- read_csv("~/Documents/GitHub/DATS-6101-group-6/data/raw/analytic_data2014.csv")


#Load 2013 Dataset
analytic_data2013 <- read_csv("~/Documents/GitHub/DATS-6101-group-6/data/raw/analytic_data2013.csv")


#Load 2012 Dataset
analytic_data2012 <- read_csv("~/Documents/GitHub/DATS-6101-group-6/data/raw/analytic_data2012.csv")

```


Step 2: Parse Variables
```{r}
#Combine Datasets




```


